### ISSUE TITLE
Lcvpn unexpectedly dying

### ISSUE THREAD

**Issue by nejtr0n** [kanocz/lcvpn#4] opened 2016-05-20 15:54 UTC
Hello. This is me again =)
My lcvpn goes down, when VM containers trying to connect through it.
Thi is log:

```
May 20 18:49:25 phy1 lcvpn[32531]: panic: runtime error: slice bounds out of range
May 20 18:49:25 phy1 lcvpn[32531]: goroutine 21 [running]:
May 20 18:49:25 phy1 lcvpn[32531]: panic(0x788de0, 0xc82000e050)
May 20 18:49:25 phy1 lcvpn[32531]: #011/usr/local/go/src/runtime/panic.go:464 +0x3e6
May 20 18:49:25 phy1 lcvpn[32531]: main.sndrThread(0xc82001e050, 0xc8200519e0)
May 20 18:49:25 phy1 lcvpn[32531]: #011/home/golang/src/github.com/kanocz/lcvpn/main.go:180 +0x192e
May 20 18:49:25 phy1 lcvpn[32531]: created by main.main
May 20 18:49:25 phy1 lcvpn[32531]: #011/home/golang/src/github.com/kanocz/lcvpn/main.go:324 +0x1384
May 20 18:49:25 phy1 systemd[1]: lcvpn.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 20 18:49:25 phy1 systemd[1]: lcvpn.service: Unit entered failed state.
May 20 18:49:25 phy1 systemd[1]: lcvpn.service: Failed with result 'exit-code'.
```

**Comment by kanocz** [comment] 2016-05-21 14:48
Hi! Very strange error... looks like corrupted (zero-size) packed received... I'll do fix next few days

**Comment by kanocz** [comment] 2016-05-21 15:26
Much more strange :) it looks like lcvpn received packet which is bigger than MTU that is set on interface :) but this can be done by changing MTU manualy... probably fixed by 9dbcc207660fda53256f7e7a175ab6d24f6adac6 - please test it in your enviropment
Thank you

**Comment by nejtr0n** [comment] 2016-05-23 09:33
This packet crashing lcvpn

```
root@phy1:~/compose# tcpdump -n -vv -i tun0 -s 0 -A -x greater 1301
tcpdump: listening on tun0, link-type RAW (Raw IP), capture size 262144 bytes
12:27:53.439599 IP (tos 0x0, ttl 64, id 4444, offset 0, flags [none], proto UDP (17), length 1500)
    10.0.0.1.47204 > 10.0.0.2.4789: [no cksum] VXLAN, flags [I] (0x08), vni 256
IP (tos 0x0, ttl 64, id 65051, offset 0, flags [DF], proto TCP (6), length 1450)
    10.10.10.6.5432 > 10.10.10.9.41734: Flags [.], cksum 0x35ae (correct), seq 242584076:242585474, ack 2311974943, win 219, options [nop,nop,TS val 2521542 ecr 2521227], length 1398
    0x0000:  4500 05dc 115c 0000 4011 4fb3 0a00 0001
    0x0010:  0a00 0002 b864 12b5 05c8 0000 0800 0000
    0x0020:  0001 0000 0242 0a0a 0a09 0242 0a0a 0a06
    0x0030:  0800 4500 05aa fe1b 4000 4006 0f10 0a0a
    0x0040:  0a06 0a0a 0a09 1538 a306 0e75 8a0c 89cd
    0x0050:  f01f 8010 00db 35ae 0000 0101 080a 0026
    0x0060:  79c6 0026 788b 3200 0000 0454 0000 0114
    0x0070:  000a 6964 0000 0041 cc00 0100 0000 1700
    0x0080:  04ff ffff ff00 0074 6974 6c65 0000 0041
    0x0090:  cc00 0200 0004 13ff ff00 0001 0300 0073
    0x00a0:  6c75 6700 0000 41cc 0003 0000 0413 ffff
    0x00b0:  0000 0103 0000 626f 6479 0000 0041 cc00
    0x00c0:  0400 0000 19ff ffff ffff ff00 0062 6f64
    0x00d0:  795f 6f72 6967 696e 616c 0000 0041 cc00
    0x00e0:  0500 0000 19ff ffff ffff ff00 0075 7365
    0x00f0:  725f 6964 0000 0041 cc00 0600 0000 1700
    0x0100:  04ff ffff ff00 0063 6174 6567 6f72 795f
    0x0110:  6964 0000 0041 cc00 0700 0000 1700 04ff
    0x0120:  ffff ff00 0063 6f6d 6d65 6e74 735f 636f
    0x0130:  756e 7400 0000 41cc 0008 0000 0017 0004
    0x0140:  ffff ffff 0000 6372 6561 7465 645f 6174
    0x0150:  0000 0041 cc00 0900 0004 5a00 08ff ffff
    0x0160:  ff00 0075 7064 6174 6564 5f61 7400 0000
    0x0170:  41cc 000a 0000 045a 0008 ffff ffff 0000
    0x0180:  4400 0000 6e00 0a00 0000 0331 3031 0000
    0x0190:  0004 5465 7374 0000 0004 7465 7374 0000
    0x01a0:  000c 3c70 3e74 6573 7421 3c2f 703e ffff
    0x01b0:  ffff 0000 0001 3100 0000 0131 0000 0001
    0x01c0:  3000 0000 1332 3031 362d 3035 2d32 3020
    0x01d0:  3133 3a35 313a 3137 0000 0013 3230 3136
    0x01e0:  2d30 352d 3230 2031 333a 3531 3a31 3744
    0x01f0:  0000 01e7 000a 0000 0001 3300 0000 4450
    0x0200:  6572 7370 6963 6961 7469 7320 6e6f 6269
    0x0210:  7320 6465 6c65 6374 7573 2061 6469 7069
    0x0220:  7363 6920 6162 2061 7574 2070 6f73 7369
    0x0230:  6d75 7320 7465 6d70 6f72 6120 6675 6769
    0x0240:  6174 2e00 0000 3869 6d70 6564 6974 2d64
    0x0250:  6967 6e69 7373 696d 6f73 2d73 6564 2d6e
    0x0260:  756d 7175 616d 2d6e 6973 692d 7665 6c2d
    0x0270:  6578 6572 6369 7461 7469 6f6e 656d 3300
    0x0280:  0000 7b41 7373 756d 656e 6461 2076 6f6c
    0x0290:  7570 7461 7320 6e75 6c6c 6120 766f 6c75
    0x02a0:  7074 6173 2e20 5265 7072 6568 656e 6465
    0x02b0:  7269 7420 6375 7069 6469 7461 7465 2064
    0x02c0:  6f6c 6f72 656d 2066 6163 696c 6973 2070
    0x02d0:  6c61 6365 6174 2071 7569 612e 2041 7471
    0x02e0:  7565 2069 7374 6520 7175 6f20 7665 6c69
    0x02f0:  7420 706f 7272 6f20 706f 7272 6f2e 0000
    0x0300:  0098 5072 6165 7365 6e74 6975 6d20 6e65
    0x0310:  7363 6975 6e74 2074 656d 706f 7269 6275
    0x0320:  7320 7265 7075 6469 616e 6461 6520 6e65
    0x0330:  7175 6520 7369 6d69 6c69 7175 6520 616c
    0x0340:  6971 7561 6d20 646f 6c6f 7265 2e20 556e
    0x0350:  6465 2075 7420 656f 7320 7061 7269 6174
    0x0360:  7572 2069 6420 6575 6d20 7175 6973 2e20
    0x0370:  5265 7072 6568 656e 6465 7269 7420 6e65
    0x0380:  7175 6520 6e6f 6e20 7369 7420 616c 6961
    0x0390:  7320 6465 6269 7469 732e 0000 0001 3700
    0x03a0:  0000 0138 0000 0001 3000 0000 1332 3031
    0x03b0:  362d 3035 2d32 3020 3133 3a35 313a 3036
    0x03c0:  0000 0013 3230 3136 2d30 352d 3230 2031
    0x03d0:  333a 3531 3a30 3644 0000 01db 000a 0000
    0x03e0:  0001 3800 0000 2a4f 6363 6165 6361 7469
    0x03f0:  2076 6f6c 7570 7461 7320 6675 6769 7420
    0x0400:  6572 726f 7220 6c61 626f 7269 6f73 616d
    0x0410:  2e00 0000 2671 7569 2d69 642d 6c61 7564
    0x0420:  616e 7469 756d 2d76 6974 6165 2d61 7065
    0x0430:  7269 616d 2d75 742d 6574 3800 0000 bb56
    0x0440:  656c 6974 2072 6572 756d 2064 6f6c 6f72
    0x0450:  656d 2071 7561 6572 6174 206f 6d6e 6973
    0x0460:  2069 6c6c 756d 206e 656d 6f2e 204f 6d6e
    0x0470:  6973 2065 7373 6520 7369 7420 6d61 696f
    0x0480:  7265 7320 6469 7374 696e 6374 696f 2e20
    0x0490:  4e6f 6269 7320 7574 2064 656c 6563 7475
    0x04a0:  7320 7375 6e74 2061 7574 2063 6f6e 7365
    0x04b0:  6374 6574 7572 2061 6d65 7420 6175 7420
    0x04c0:  6e69 6869 6c2e 2045 7420 6561 2075 6c6c
    0x04d0:  616d 2064 6973 7469 6e63 7469 6f20 7175
    0x04e0:  6173 6920 6574 2070 6572 7370 6963 6961
    0x04f0:  7469 7320 6375 6c70 612e 0000 0078 556e
    0x0500:  6465 2069 7073 616d 2074 656d 706f 7265
    0x0510:  2072 6570 7265 6865 6e64 6572 6974 2061
    0x0520:  7574 2065 7870 6c69 6361 626f 2e20 5574
    0x0530:  206e 6f73 7472 756d 2064 7563 696d 7573
    0x0540:  2076 656c 6974 2073 696e 7420 7175 6961
    0x0550:  2065 7374 2e20 4561 2062 6c61 6e64 6974
    0x0560:  6969 7320 7175 6964 656d 2069 7073 756d
    0x0570:  2065 6e69 6d2e 0000 0001 3600 0000 0132
    0x0580:  0000 0001 3000 0000 1332 3031 362d 3035
    0x0590:  2d32 3020 3133 3a35 313a 3036 0000 0013
    0x05a0:  3230 3136 2d30 352d 3230 2031 333a 3531
    0x05b0:  3a30 3644 0000 01ab 000a 0000 0001 3500
    0x05c0:  0000 3951 7569 2064 656c 6563 7475 7320
    0x05d0:  6675 6769 6174 2076 6f6c 7570
12:27:53.439613 IP (tos 0x0, ttl 64, id 4445, offset 0, flags [none], proto UDP (17), length 1500)
    10.0.0.1.47204 > 10.0.0.2.4789: [no cksum] VXLAN, flags [I] (0x08), vni 256
IP (tos 0x0, ttl 64, id 65052, offset 0, flags [DF], proto TCP (6), length 1450)
    10.10.10.6.5432 > 10.10.10.9.41734: Flags [.], cksum 0x1c06 (correct), seq 1398:2796, ack 1, win 219, options [nop,nop,TS val 2521542 ecr 2521227], length 1398
    0x0000:  4500 05dc 115d 0000 4011 4fb2 0a00 0001
    0x0010:  0a00 0002 b864 12b5 05c8 0000 0800 0000
    0x0020:  0001 0000 0242 0a0a 0a09 0242 0a0a 0a06
    0x0030:  0800 4500 05aa fe1c 4000 4006 0f0f 0a0a
    0x0040:  0a06 0a0a 0a09 1538 a306 0e75 8f82 89cd
    0x0050:  f01f 8010 00db 1c06 0000 0101 080a 0026
    0x0060:  79c6 0026 788b 7461 7475 6d20 646f 6c6f
    0x0070:  7265 6d20 7465 6d70 6f72 6962 7573 2065
    0x0080:  7420 6175 742e 0000 0011 6f64 6974 2d65
    0x0090:  6e69 6d2d 7175 6f2d 6574 3500 0000 9a41
    0x00a0:  7574 2072 6570 7265 6865 6e64 6572 6974
    0x00b0:  2064 6f6c 6f72 656d 7175 6520 6e69 6869
    0x00c0:  6c20 7365 7175 692e 2045 7420 6574 2071
    0x00d0:  756f 2065 6c69 6765 6e64 6920 7175 6165
    0x00e0:  2063 6f6e 7365 7175 756e 7475 7220 7072
    0x00f0:  6165 7365 6e74 6975 6d20 7365 7175 692e
    0x0100:  204d 6178 696d 6520 6d6f 6c65 7374 6961
    0x0110:  6520 6469 7374 696e 6374 696f 206e 6174
    0x0120:  7573 2065 6c69 6765 6e64 6920 6561 7275
    0x0130:  6d20 646f 6c6f 7265 2e00 0000 6e45 7420
    0x0140:  636f 6e73 6571 7575 6e74 7572 2071 756f
    0x0150:  2061 7574 2062 6561 7461 6520 6465 7365
    0x0160:  7275 6e74 2061 6c69 7175 6964 206d 6178
    0x0170:  696d 652e 2050 726f 7669 6465 6e74 2070
    0x0180:  7261 6573 656e 7469 756d 2072 6572 756d
    0x0190:  2061 6469 7069 7363 6920 6970 7375 6d20
    0x01a0:  7265 7275 6d20 656e 696d 2e00 0000 0231
    0x01b0:  3800 0000 0135 0000 0001 3000 0000 1332
    0x01c0:  3031 362d 3035 2d32 3020 3133 3a35 313a
    0x01d0:  3036 0000 0013 3230 3136 2d30 352d 3230
    0x01e0:  2031 333a 3531 3a30 3644 0000 01a5 000a
    0x01f0:  0000 0001 3600 0000 3145 6120 646f 6c6f
    0x0200:  7265 7320 766f 6c75 7074 6174 6573 206f
    0x0210:  6666 6963 6961 2061 6c69 7175 616d 2071
    0x0220:  7569 6120 6561 7275 6d2e 0000 0037 706f
    0x0230:  7272 6f2d 6561 2d6e 6973 692d 7369 6e74
    0x0240:  2d6f 6d6e 6973 2d73 6564 2d61 6363 7573
    0x0250:  616d 7573 2d72 6570 656c 6c65 6e64 7573
    0x0260:  2d73 6974 3600 0000 9e41 7263 6869 7465
    0x0270:  6374 6f20 766f 6c75 7074 6174 6962 7573
    0x0280:  2072 6570 656c 6c61 7420 636f 7272 7570
    0x0290:  7469 2074 656d 706f 7269 6275 732e 2044
    0x02a0:  6f6c 6f72 6573 2061 6469 7069 7363 6920
    0x02b0:  7369 6e74 2074 656d 706f 7265 2066 7567
    0x02c0:  612e 204e 756d 7175 616d 2070 7261 6573
    0x02d0:  656e 7469 756d 2070 6572 6665 7265 6e64
    0x02e0:  6973 2064 6f6c 6f72 206e 6563 6573 7369
    0x02f0:  7461 7469 6275 7320 696c 6c75 6d20 7361
    0x0300:  7069 656e 7465 2e00 0000 4652 6570 656c
    0x0310:  6c61 7420 6574 2061 7574 656d 2064 6f6c
    0x0320:  6f72 2065 6f73 2065 6171 7565 2069 7073
    0x0330:  756d 2e20 566f 6c75 7074 6174 656d 2065
    0x0340:  6172 756d 2061 7420 6e65 7363 6975 6e74
    0x0350:  2e00 0000 0231 3100 0000 0133 0000 0001
    0x0360:  3000 0000 1332 3031 362d 3035 2d32 3020
    0x0370:  3133 3a35 313a 3036 0000 0013 3230 3136
    0x0380:  2d30 352d 3230 2031 333a 3531 3a30 3644
    0x0390:  0000 01ed 000a 0000 0001 3700 0000 3252
    0x03a0:  6570 656c 6c61 7420 646f 6c6f 7265 6d71
    0x03b0:  7565 2071 756f 2065 756d 2070 6172 6961
    0x03c0:  7475 7220 6869 6320 6e61 7475 7320 6574
    0x03d0:  2e00 0000 2965 6e69 6d2d 6d6f 6c65 7374
    0x03e0:  6961 652d 6162 2d69 642d 6375 7069 6469
    0x03f0:  7461 7465 2d75 742d 6e69 6869 6c37 0000
    0x0400:  0099 4469 7374 696e 6374 696f 2061 7574
    0x0410:  656d 206d 6167 6e61 6d20 7072 6165 7365
    0x0420:  6e74 6975 6d20 6573 7420 6578 2e20 456f
    0x0430:  7320 6469 676e 6973 7369 6d6f 7320 636f
    0x0440:  7272 7570 7469 206e 6968 696c 2069 7461
    0x0450:  7175 6520 6e69 6869 6c2e 2041 7574 656d
    0x0460:  2069 6e20 6975 7265 2072 6569 6369 656e
    0x0470:  6469 732e 2049 7374 6520 6469 6374 6120
    0x0480:  6970 7361 2071 7569 2068 6172 756d 2070
    0x0490:  6572 6665 7265 6e64 6973 2e00 0000 a153
    0x04a0:  6564 2073 6974 2064 6973 7469 6e63 7469
    0x04b0:  6f20 6561 7175 6520 7465 6d70 6f72 6120
    0x04c0:  6561 7175 652e 204d 6178 696d 6520 6375
    0x04d0:  7069 6469 7461 7465 2065 6120 6174 2069
    0x04e0:  6420 7465 6d70 6f72 6962 7573 2070 6f73
    0x04f0:  7369 6d75 732e 204e 6174 7573 206e 6f6e
    0x0500:  2061 6c69 6173 2069 6e20 6265 6174 6165
    0x0510:  2065 7373 6520 646f 6c6f 7275 6d2e 2053
    0x0520:  696e 7420 656f 7320 6573 7420 6375 6c70
    0x0530:  6120 6e6f 6e20 696e 7665 6e74 6f72 652e
    0x0540:  0000 0001 3100 0000 0132 0000 0001 3000
    0x0550:  0000 1332 3031 362d 3035 2d32 3020 3133
    0x0560:  3a35 313a 3036 0000 0013 3230 3136 2d30
    0x0570:  352d 3230 2031 333a 3531 3a30 3644 0000
    0x0580:  01ca 000a 0000 0001 3400 0000 1645 6c69
    0x0590:  6765 6e64 6920 7574 206e 6968 696c 2071
    0x05a0:  7569 2e00 0000 2265 7665 6e69 6574 2d64
    0x05b0:  6f6c 6f72 656d 2d72 6572 756d 2d65 742d
    0x05c0:  696e 6369 6475 6e74 3400 0000 744e 6f6e
    0x05d0:  2065 7373 6520 7072 6f76 6964
12:27:53.439616 IP (tos 0x0, ttl 64, id 4446, offset 0, flags [none], proto UDP (17), length 1500)
    10.0.0.1.47204 > 10.0.0.2.4789: [no cksum] VXLAN, flags [I] (0x08), vni 256
IP (tos 0x0, ttl 64, id 65053, offset 0, flags [DF], proto TCP (6), length 1450)
    10.10.10.6.5432 > 10.10.10.9.41734: Flags [.], cksum 0x9e0b (correct), seq 2796:4194, ack 1, win 219, options [nop,nop,TS val 2521542 ecr 2521227], length 1398
    0x0000:  4500 05dc 115e 0000 4011 4fb1 0a00 0001
    0x0010:  0a00 0002 b864 12b5 05c8 0000 0800 0000
    0x0020:  0001 0000 0242 0a0a 0a09 0242 0a0a 0a06
    0x0030:  0800 4500 05aa fe1d 4000 4006 0f0e 0a0a
    0x0040:  0a06 0a0a 0a09 1538 a306 0e75 94f8 89cd
    0x0050:  f01f 8010 00db 9e0b 0000 0101 080a 0026
    0x0060:  79c6 0026 788b 656e 7420 7369 742e 2049
    0x0070:  7073 616d 206c 6962 6572 6f20 6c61 626f
    0x0080:  7275 6d20 696e 6369 6475 6e74 2065 7373
    0x0090:  652e 2051 7561 6572 6174 2071 7569 6465
    0x00a0:  6d20 7265 7072 6568 656e 6465 7269 7420
    0x00b0:  7574 2063 6f6e 7365 6374 6574 7572 2073
    0x00c0:  6165 7065 206f 6d6e 6973 2e00 0000 c554
    0x00d0:  6f74 616d 2069 7073 6120 7175 6962 7573
    0x00e0:  6461 6d20 696c 6c75 6d20 696d 7065 6469
    0x00f0:  7420 6173 7065 726e 6174 7572 2e20 5175
    0x0100:  6920 7369 6d69 6c69 7175 6520 6469 676e
    0x0110:  6973 7369 6d6f 7320 6964 2075 7420 766f
    0x0120:  6c75 7074 6174 656d 2e20 4465 6269 7469
    0x0130:  7320 646f 6c6f 7275 6d20 7665 726f 2063
    0x0140:  6f6e 7365 7175 756e 7475 7220 7369 7420
    0x0150:  6574 2064 6963 7461 2061 7370 6572 6e61
    0x0160:  7475 722e 2056 6f6c 7570 7461 7475 6d20
    0x0170:  7261 7469 6f6e 6520 6d61 676e 616d 2061
    0x0180:  7420 6573 7420 6e69 6869 6c20 6574 2071
    0x0190:  7561 652e 0000 0002 3233 0000 0001 3500
    0x01a0:  0000 0130 0000 0013 3230 3136 2d30 352d
    0x01b0:  3230 2031 333a 3531 3a30 3600 0000 1332
    0x01c0:  3031 362d 3035 2d32 3020 3133 3a35 313a
    0x01d0:  3036 4400 0001 da00 0a00 0000 0139 0000
    0x01e0:  0037 5375 6e74 2076 6f6c 7570 7461 7469
    0x01f0:  6275 7320 6e61 7475 7320 6d6f 6c65 7374
    0x0200:  6961 7320 6e69 7369 2073 6974 2076 656c
    0x0210:  6974 2064 6f6c 6f72 2e00 0000 2876 6572
    0x0220:  6f2d 7261 7469 6f6e 652d 7175 6961 2d61
    0x0230:  7574 2d69 6c6c 756d 2d70 6572 6665 7265
    0x0240:  6e64 6973 3900 0000 9045 6e69 6d20 6661
    0x0250:  6365 7265 2069 7073 756d 2061 7065 7269
    0x0260:  616d 2e20 506f 7272 6f20 6c61 626f 7269
    0x0270:  6f73 616d 2065 6e69 6d20 7175 6964 656d
    0x0280:  2076 656c 6974 2065 6975 732e 2053 6974
    0x0290:  2061 6e69 6d69 2072 6572 756d 206e 6973
    0x02a0:  6920 6175 7420 6578 6365 7074 7572 6920
    0x02b0:  656c 6967 656e 6469 2075 742e 2051 7569
    0x02c0:  6120 6d6f 6469 2065 7420 6578 6365 7074
    0x02d0:  7572 6920 6573 7365 2e00 0000 9245 6120
    0x02e0:  616c 6971 7569 6420 6569 7573 2063 7570
    0x02f0:  6964 6974 6174 6520 7265 6963 6965 6e64
    0x0300:  6973 2071 7561 7369 206e 6968 696c 2e20
    0x0310:  4164 6970 6973 6369 206c 6162 6f72 6520
    0x0320:  6970 7375 6d20 7175 6964 656d 2073 696d
    0x0330:  696c 6971 7565 2e20 5375 6e74 2074 656d
    0x0340:  706f 7265 2066 6163 6572 6520 656c 6967
    0x0350:  656e 6469 206f 6d6e 6973 2072 6174 696f
    0x0360:  6e65 2061 6220 7574 2073 6571 7569 2e00
    0x0370:  0000 0231 3700 0000 0135 0000 0001 3000
    0x0380:  0000 1332 3031 362d 3035 2d32 3020 3133
    0x0390:  3a35 313a 3036 0000 0013 3230 3136 2d30
    0x03a0:  352d 3230 2031 333a 3531 3a30 3644 0000
    0x03b0:  014c 000a 0000 0001 3200 0000 1754 656d
    0x03c0:  706f 7265 2065 6120 7175 6f73 2066 7567
    0x03d0:  6961 742e 0000 0018 6175 742d 6375 6d71
    0x03e0:  7565 2d65 6e69 6d2d 6174 2d71 7569 7332
    0x03f0:  0000 0049 4c61 626f 7275 6d20 6e69 6869
    0x0400:  6c20 646f 6c6f 7269 6275 7320 6e65 7363
    0x0410:  6975 6e74 2073 696e 742e 2049 6d70 6564
    0x0420:  6974 2066 7567 6120 7574 2073 756e 7420
    0x0430:  6578 706c 6963 6162 6f20 6574 2e00 0000
    0x0440:  7b56 6974 6165 2071 7561 7320 6e6f 7374
    0x0450:  7275 6d20 766f 6c75 7074 6173 2071 7569
    0x0460:  6120 736f 6c75 7461 2064 6f6c 6f72 6573
    0x0470:  2e20 4175 7420 6569 7573 2063 756c 7061
    0x0480:  2064 6f6c 6f72 656d 2070 6f73 7369 6d75
    0x0490:  7320 6561 7275 6d20 646f 6c6f 722e 2044
    0x04a0:  6f6c 6f72 656d 2073 6564 2073 6564 206e
    0x04b0:  6573 6369 756e 7420 7175 692e 0000 0002
    0x04c0:  3130 0000 0001 3400 0000 0130 0000 0013
    0x04d0:  3230 3136 2d30 352d 3230 2031 333a 3531
    0x04e0:  3a30 3600 0000 1332 3031 362d 3035 2d32
    0x04f0:  3020 3133 3a35 313a 3036 4400 0001 b700
    0x0500:  0a00 0000 0231 3000 0000 2d4e 6f6e 2064
    0x0510:  656c 6563 7475 7320 6c61 626f 7269 6f73
    0x0520:  616d 2061 7263 6869 7465 6374 6f20 7175
    0x0530:  6962 7573 6461 6d2e 0000 002b 6e61 6d2d
    0x0540:  6d6f 6c6c 6974 6961 2d61 6c69 7175 616d
    0x0550:  2d6d 696e 696d 612d 6574 2d61 7263 6869
    0x0560:  7465 6374 6f31 3000 0000 9451 7561 6572
    0x0570:  6174 206e 6f6e 2072 6563 7573 616e 6461
    0x0580:  6520 7175 6165 2073 756e 7420 6675 6769
    0x0590:  742e 2054 656d 706f 7269 6275 7320 6576
    0x05a0:  656e 6965 7420 626c 616e 6469 7469 6973
    0x05b0:  206d 6f6c 6573 7469 6173 2071 7569 6465
    0x05c0:  6d20 7175 6173 2063 6f6e 7365 6374 6574
    0x05d0:  7572 206e 756c 6c61 2e20 5175
tcpdump: pcap_loop: The interface went down
3 packets captured
3 packets received by filter
0 packets dropped by kernel
```

Problem is that docker gateway_bridge interface has mtu 1500, and it conect through tun0 with 1300.
 But i thought kernel should repack packets... Am i right?
Maybe it would be more flexible to change MTU for lcvpn from config file?

**Comment by kanocz** [comment] 2016-05-24 14:48
confirmed as fixed

**Closed as completed by kanocz** 2016-05-24 14:48 UTC
